FROM node:latest
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm install
COPY . /usr/src/app
EXPOSE 8081
ENV inituser=admin
ENV initpw=admin
CMD [ "npm", "start" ]
